config/routes.rb
Rails.application.routes.draw do
 
  resources :receipts, except: :show
  resources :trays
  
  root "receipts#index"
  
  get '/home' => 'receipts#index'
  get '/login' => redirect('/auth/google_oauth2')
  get '/signup' => 'users#new'
  get '/goodbye' => 'sessions#goodbye'
  delete '/logout' => 'sessions#destroy' 

  get '/auth/:provider/callback' => 'sessions#omniauth'

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  has_many :receipts
  validates_uniqueness_of :name
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :user
  belongs_to :tray
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  include Discard::Model

  belongs_to :creator, class_name: 'User', foreign_key: 'created_by'
  belongs_to :tray
  belongs_to :merchant, optional: true 

  has_many_attached :images
  
  after_create :broadcast

  def broadcast
    ActionCable.server.broadcast("receipts",
      content: ApplicationController.renderer.render(
        partial: 'receipts/receipt', locals: {
          receipt: self
        }))
  end

  def date
    transaction_date || created_at
  end
end

app/models/tray.rb
class Tray < ApplicationRecord
  has_many :permissions
  has_many :users, through: :permissions

  has_many :receipts

  scope :writable, -> { where("access = 'readwrite'") }


  # validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :permissions
  has_many :trays, through: :permissions
  has_many :receipts, through: :trays

  after_create :create_tray

  # PERMITTED_SENDERS = ENV['PERMITTED_SENDERS'].split(',')
  # PERMITTED_USERS = ENV['PERMITTED_USERS'].split(',')

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_initialize do |user|
      user.user_name = auth.info.name
      user.email = auth.info.email
      user.image = auth.info.image
      user.password = SecureRandom.hex
    end
  end

  def default_tray
    trays.where(default: true).first
  end

  private
  def create_tray
    permissions.create(access:'readwrite', tray: Tray.create(name: 'Default', default: true))
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  before_action :require_login

  layout :determine_layout

  def determine_layout
    if logged_in?
      'authed'
    else
      'unauthed'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  def index
    if params[:tray_id]
      @tray = current_user.trays.find(params[:tray_id])
      @receipts = @tray.receipts.kept
    elsif params[:merchant_id]
      @merchant = Merchant.find params[:merchant_id]
      @receipts = @merchant.receipts # needs to be done through trays to return readable receipts
    else
      @receipts = current_user.receipts.kept
    end
    @receipts = @receipts.order("transaction_date DESC")
  end

  def new
    @receipt = Receipt.new
    @merchants = Merchant.all
  end

  def edit
    @receipt = current_user.receipts.find(params[:id])
  end

  def create
    if receipt_params[:merchant] == 'new'
      @merchant = Merchant.create(name: receipt_params[:merchant_name])
      @receipt = Receipt.new(receipt_params.except(:merchant_name).merge(creator: current_user, merchant: @merchant))
    else
      @receipt = Receipt.new(receipt_params.except(:merchant, :merchant_name).merge(creator: current_user))
    end

    if @receipt.save
      redirect_to receipts_path
    else
      raise @receipt.errors.inspect
    end

  end

  def update
    @receipt = current_user.receipts.find(params[:id])
    if receipt_params[:merchant] == 'new'
      @merchant = Merchant.create(name: receipt_params[:merchant_name])
      @receipt.update receipt_params.except(:merchant, :merchant_name).merge(merchant: @merchant)
    else
      @receipt.update receipt_params.except(:merchant, :merchant_name) 
    end

      redirect_to edit_receipt_path(@receipt.id)

  end

  def destroy
    @receipt = current_user.receipts.find(params[:id])
    @receipt.discard

    redirect_to receipts_path
  end

  def receipt_params
    params.require(:receipt).permit(:tray_id, :merchant_id, :merchant, :merchant_name, :transaction_date, :amount, images: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login
  before_action :ensure_email_permitted, only: :omniauth

  def omniauth
    @user = User.from_omniauth(auth)
    if @user.save
      session[:user_id] = @user.id
      redirect_to home_path
    else
      render :not_found
    end
  end

  def destroy
    session.clear
    redirect_to '/goodbye'
  end

  def goodbye
  end
  
  private
  def auth
    request.env['omniauth.auth']
  end

  def ensure_email_permitted
    unless ENV['PERMITTED_USERS'].include? auth.info.email
      flash[:error] = "You don't have access, speak to your family"
      redirect_to login_path # halts request cycle
    end
  end
end

app/controllers/trays_controller.rb
class TraysController < ApplicationController
  def index
    @permissions = current_user.permissions
  end

  def show
    @tray = current_user.trays.find(params[:id])
  end

  def new
    @tray = Tray.new
  end

  def edit
    @tray = current_user.trays.find(params[:id])
  end

  def create
    @tray = Tray.new(tray_params)
    if @tray.save
      current_user.permissions.create(access:'readwrite', tray: @tray)
      redirect_to trays_path
    else
      raise @receipt.trays.inspect
    end
   end

  def tray_params
    params.require(:tray).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login

  def new
    @invite = Invitation.find_by_token(params[:token])
    if @invite
      redirect_to '/auth/google_oauth2'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #creates instance variable for current user
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  #checks if user is logged in
  def logged_in?
    !!session[:user_id]
  end

  #creates before action
  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to login_path # halts request cycle
    end
  end
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/home/index.html.erb
<%= link_to "Log In with Google", '/auth/google_oauth2' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('keeper.appname') %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/holder/2.9.7/holder.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"><%= t('keeper.appname') %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
        <%# <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Trays
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "All", receipts_path, class: 'dropdown-item' %>
          <% current_user.trays.each do |tray| %>
            <%= link_to tray.name, receipts_path(tray_id: tray.id), class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.user_name %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" data-method="delete" href="/logout">Logout</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<div class="container">
<%= yield %>

</div>

    
    
  </body>
</html>

app/views/layouts/authed.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('keeper.appname') %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/holder/2.9.7/holder.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
  </head>

  <body>
    <div class="bg-gray-100">
      <%= render ::NavBar::Component.new(current_user: current_user) %>
      <main>
        <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
          <%= yield %>
        </div>
      </main>
    </div>
  </body>
</html>

app/views/layouts/unauthed.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('keeper.appname') %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/holder/2.9.7/holder.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/receipts/_form.html.erb
<div class="form-group row">
<%= f.label :tray_id, class: 'col-sm-2 col-form-label' %>
  <div class="col-sm-10">
    <%= f.select(:tray_id, current_user.trays.writable.collect {|t| [ t.name, t.id ] }, {}, {class: 'form-control'})%>
  </div>
</div>

<fieldset class="form-group">
    <div class="row">
      <legend class="col-form-label col-sm-2 pt-0">Merchant</legend>
      <div class="col-sm-10">
        <div class="form-check">
          <input class="form-check-input" type="radio" name="receipt[merchant]" id="gridRadios1" value="existing" checked>
          <label class="form-check-label" for="gridRadios1">
            Existing
          </label>
          <%= f.select(:merchant_id, Merchant.all.collect {|t| [ t.name, t.id ] }, {}, {class: 'form-control'})%>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="receipt[merchant]" id="gridRadios2" value="new">
          <label class="form-check-label" for="gridRadios2">
            Add New
          </label>
          <input class="form-control" type="input" name="receipt[merchant_name]" %>
        </div>
      </div>
    </div>
  </fieldset>

<div class="form-group row">
<%= f.label :transaction_date, class: 'col-sm-2 col-form-label' %>
  <div class="col-sm-10">
    <%= f.date_field :transaction_date %>
  </div>
</div>


<div class="form-group row">
<%= f.label :amount, class: 'col-sm-2 col-form-label' %>
  <div class="col-sm-10">
    <%= f.text_field :amount %>
  </div>
</div>

<div class="form-group row">
<%= f.label :images, class: 'col-sm-2 col-form-label' %>
  <div class="col-sm-10">
    <%= f.file_field :images, multiple: true %>
  </div>
</div>

app/views/receipts/_receipt.html.erb
I AM A RECEIPT

app/views/receipts/edit.html.erb
<%= render HeaderComponent.new(title: 'Editing Receipt') %>

<%= form_for(@receipt) do |f| %>
<div class="form-group row">
<%= f.label :tray_id, class: 'col-sm-2 col-form-label' %>
  <div class="col-sm-10">
    <%= f.select(:tray_id, current_user.trays.writable.collect {|t| [ t.name, t.id ] }, {}, {class: 'form-control'})%>
  </div>
</div>

<fieldset class="form-group">
    <div class="row">
      <legend class="col-form-label col-sm-2 pt-0">Merchant</legend>
        <div class="col-sm-10">
        <div class="form-check">
          <input class="form-check-input" type="radio" name="receipt[merchant]" id="gridRadios1" value="existing" checked>
          <label class="form-check-label" for="gridRadios1">
            Existing
          </label>
          <%= f.select(:merchant_id, Merchant.all.collect {|t| [ t.name, t.id ] }, {}, {class: 'form-control'})%>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="receipt[merchant]" id="gridRadios2" value="new">
          <label class="form-check-label" for="gridRadios2">
            Add New
          </label>
          <input class="form-control" type="input" name="receipt[merchant_name]" %>
        </div>
      </div>
    </div>
  </fieldset>


  <div class="form-group row">
<%= f.label :transaction_date, class: 'col-sm-2 col-form-label' %>
  <div class="col-sm-10">
    <%= f.date_field :transaction_date %>
  </div>
</div>



<div class="form-group row">
<%= f.label :amount, class: 'col-sm-2 col-form-label' %>
  <div class="col-sm-10">
    <%= f.text_field :amount %>
  </div>
</div>

<%= f.label :images %>
<%= f.file_field :images, multiple: true %>

<ul>
  <% @receipt.images.each do |file| %>
    <li>
    <% if file.previewable? %>
      <%= link_to image_tag(file.preview(resize_to_limit: [200, 200])), file %>
    <% elsif file.variable? %>
        <%= link_to image_tag(file.variant(resize: "200x200^")), file %>
    <% else %>
      <%= link_to "View", file %>
    <% end %>
    </li>
  <% end %>
</ul>

 <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Delete', receipt_path(@receipt), method: 'delete' %>
  </div>

<% end %>

app/views/receipts/index.html.erb
<%= render HeaderComponent.new(title: 'All Receipts') %>


<% if @receipts.present? %>
 <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5">
 
  <% @receipts.each do |receipt| %>
    <%= render ::ReceiptCard::Component.new(receipt: receipt) %>
  <% end %>
  
  </div>
<% else %>
  You don't have any receipts yet. Why now add one?
<% end %>

app/views/receipts/new.html.erb
<h2>Add a new receipt</h2>

<%= form_for(@receipt) do |f| %>
<div class="form-group row">
<%= f.label :tray_id, class: 'col-sm-2 col-form-label' %>
  <div class="col-sm-10">
    <%= f.select(:tray_id, current_user.trays.writable.collect {|t| [ t.name, t.id ] }, {}, {class: 'form-control'})%>
  </div>
</div>

<fieldset class="form-group">
    <div class="row">
      <legend class="col-form-label col-sm-2 pt-0">Merchant</legend>
      <div class="col-sm-10">
        <div class="form-check">
          <input class="form-check-input" type="radio" name="receipt[merchant]" id="gridRadios1" value="existing" checked>
          <label class="form-check-label" for="gridRadios1">
            Existing
          </label>
          <%= f.select(:merchant_id, @merchants.collect {|t| [ t.name, t.id ] }, {}, {class: 'form-control', disabled: @merchants.present? ? false : true })%>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="receipt[merchant]" id="gridRadios2" value="new" <% if !@merchants.present? %>checked<% end %>>
          <label class="form-check-label" for="gridRadios2">
            Add New
          </label>
          <input class="form-control" type="input" name="receipt[merchant_name]" %>
        </div>
      </div>
    </div>
  </fieldset>

<div class="form-group row">
<%= f.label :transaction_date, class: 'col-sm-2 col-form-label' %>
  <div class="col-sm-10">
    <%= f.date_field :transaction_date %>
  </div>
</div>


<div class="form-group row">
<%= f.label :amount, class: 'col-sm-2 col-form-label' %>
  <div class="col-sm-10">
    <%= f.text_field :amount %>
  </div>
</div>

<div class="form-group row">
<%= f.label :images, class: 'col-sm-2 col-form-label' %>
  <div class="col-sm-10">
    <%= f.file_field :images, multiple: true %>
  </div>
</div>

 <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/receipts/show.html.erb
<% @receipt.images.each do |image| %>
  <%= image_tag url_for(image) %>
<% end %>

app/views/trays/edit.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
<h2>
  Editing Tray: <%= @tray.name %>
</h2>

</div>

<% @tray.permissions.each do |permission| %>
  <%= permission.user.user_name %>(<%= permission.user.email %>) - <%= permission.access %><br />
<% end %>

app/views/trays/index.html.erb
<ul>
<% @permissions.each do |permission| %>
<li>
  <%= link_to permission.tray.name, edit_tray_path(permission.tray.id) %> <%=  permission.access %>
</li>
<% end %>
</ul>

<section class="px-4 sm:px-6 lg:px-4 xl:px-6 pt-4 pb-4 sm:pb-6 lg:pb-4 xl:pb-6 space-y-4">
  <header class="flex items-center justify-between">
    <h2 class="text-lg leading-6 font-medium text-black">Trays</h2>
    <button class="hover:bg-light-blue-200 hover:text-light-blue-800 group flex items-center rounded-md bg-light-blue-100 text-light-blue-600 text-sm font-medium px-4 py-2">
      <svg class="group-hover:text-light-blue-600 text-light-blue-500 mr-2" width="12" height="20" fill="currentColor">
        <path fill-rule="evenodd" clip-rule="evenodd" d="M6 5a1 1 0 011 1v3h3a1 1 0 110 2H7v3a1 1 0 11-2 0v-3H2a1 1 0 110-2h3V6a1 1 0 011-1z"/>
      </svg>
      New
    </button>
  </header>
  <form class="relative">
    <svg width="20" height="20" fill="currentColor" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400">
      <path fill-rule="evenodd" clip-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" />
    </svg>
    <input class="focus:border-light-blue-500 focus:ring-1 focus:ring-light-blue-500 focus:outline-none w-full text-sm text-black placeholder-gray-500 border border-gray-200 rounded-md py-2 pl-10" type="text" aria-label="Filter projects" placeholder="Filter trays" />
  </form>
  <ul class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2 gap-4">
  <% @permissions.each do |permission| %>
    <%= render ::TrayCard::Component.new(permission: permission) %>
  <% end %>
    
    <li class="hover:shadow-lg flex rounded-lg">
    <%= link_to 'New Tray', new_tray_path, class: "hover:border-transparent hover:shadow-xs w-full flex items-center justify-center rounded-lg border-2 border-dashed border-gray-200 text-sm font-medium py-4" %>
    </li>
  </ul>
</section>

app/views/trays/new.html.erb
<h2>New Tray</h2>

<%= form_for(@tray) do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

 <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/trays/show.html.erb
<%= raise @tray.inspect %>